name: Deploy to Cloud Run from Source

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: slack-financial-reporter
  PROJECT_NUMBER: "345012852320"
  REGION: us-east1
  SERVICE: slack-financial-reporter
  WORKLOAD_IDENTITY_PROVIDER: "projects/345012852320/locations/global/workloadIdentityPools/github-action-cloud-run/providers/github"
  SERVICE_ACCOUNT_EMAIL: "github-actions@slack-financial-reporter.iam.gserviceaccount.com"
  SERVICE_ACCOUNT: "projects/slack-financial-reporter/serviceAccounts/github-actions@slack-financial-reporter.iam.gserviceaccount.com"
  BUILD_SERVICE_ACCOUNT: "projects/slack-financial-reporter/serviceAccounts/cloud-run-builder@slack-financial-reporter.iam.gserviceaccount.com"

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT_EMAIL }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE }} \
            --project=${{ env.PROJECT_ID }} \
            --region=${{ env.REGION }} \
            --source=. \
            --service-account=${{ env.SERVICE_ACCOUNT_EMAIL }} \
            --build-service-account=${{ env.BUILD_SERVICE_ACCOUNT }}
